-- AlterEnum
ALTER TABLE `audit_logs` MODIFY `action` ENUM('ADMIN_LOGIN', 'ADMIN_USER_CREATED', 'ADMIN_USER_UPDATED', 'ADMIN_USER_DISABLED', 'ADMIN_USER_PASSWORD_RESET', 'BRANCH_CREATED', 'BRANCH_UPDATED', 'BRANCH_DELETED', 'TABLE_CREATED', 'TABLE_UPDATED', 'MENU_CREATED', 'MENU_UPDATED', 'MENU_DELETED', 'ORDER_STATUS_UPDATED', 'PAYMENT_CONFIRMED', 'MENU_IMAGE_UPLOADED') NOT NULL;

-- AlterTable
ALTER TABLE `admin_users` ADD COLUMN `is_active` BOOLEAN NOT NULL DEFAULT true;
